teamName_dict = {'Manchester United':'แมนเชสเตอร์ ยูไนเต็ด',
                 'Newcastle':'นิวคาสเซิล',
                 'Fulham':'ฟูแล่ม', 
                 'Wolves': 'วูล์ฟแฮมป์ตัน', 
                 'Liverpool':'ลิเวอร์พูล', 
                 'Southampton':'เซาแทมป์ตัน', 
                 'Arsenal':'อาร์เซน่อล', 
                 'Burnley':'เบิร์นลี่', 
                 'Everton':'เอฟเวอร์ตัน', 
                 'Leicester':'เลสเตอร์ ซิตี้', 
                 'Tottenham':'ท็อตแน่ม ฮอตสเปอร์', 
                 'West Ham':'เวสต์แฮม ยูไนเต็ด', 
                 'Chelsea':'เชลซี', 
                 'Manchester City':'แมนเชสเตอร์ ซิตี้', 
                 'Brighton':'ไบรท์ตัน', 
                 'Crystal Palace':'คริสตัล พาเลซ', 
                 'West Brom':'เวสต์บรอมวิช อัลเบี้ยน', 
                 'Sheffield Utd':'เชฟฟิลด์ ยูไนเต็ด', 
                 'Leeds':'ลีดส์ ยูไนเต็ด', 
                 'Aston Villa':'แอสตัน วิลล่า',
                 'Watford':'วัตฟอร์ด',
                 'Brentford':'เบรนท์ฟอร์ด',
                 'Norwich':'นอริช ซิตี้'
                 }

