teamName_dict = {'Manchester United':'แมนเชสเตอร์ ยูไนเต็ด',
                 'Newcastle':'นิวคาสเซิล',
                 'Fulham':None, 
                 'Wolves': None, 
                 'Liverpool':'ลิเวอร์พูล', 
                 'Southampton':None, 
                 'Arsenal':'อาร์เซน่อล', 
                 'Burnley':'เบิร์นลี่', 
                 'Everton':'เอฟเวอร์ตัน', 
                 'Leicester':'เลสเตอร์ ซิตี้', 
                 'Tottenham':None, 
                 'West Ham':'เวสต์แฮม ยูไนเต็ด', 
                 'Chelsea':'เชลซี', 
                 'Manchester City':None, 
                 'Brighton':'ไบรท์ตัน', 
                 'Crystal Palace':'คริสตัล พาเลซ', 
                 'West Brom':'เวสต์บรอมวิช อัลเบี้ยน', 
                 'Sheffield Utd':'เชฟฟิลด์ ยูไนเต็ด', 
                 'Leeds':'ลีดส์ ยูไนเต็ด', 
                 'Aston Villa':'แอสตัน วิลล่า'
                 }